# Generated by Django 5.2.5 on 2025-12-04 19:26

import ProInvPunDeVenAPI.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('IdBodega', models.AutoField(db_column='IdBodega', primary_key=True, serialize=False, verbose_name='Id Bodega')),
                ('NombreBodega', models.CharField(db_column='NombreBodega', max_length=20, validators=[ProInvPunDeVenAPI.models.Bodegas.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(5, message='Debes ingresar minimo 5 caracteres')], verbose_name='Nombre')),
                ('UbicacionBodega', models.CharField(db_column='UbicacionBodega', max_length=30, validators=[ProInvPunDeVenAPI.models.Bodegas.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(5, message='Debes ingresar minimo 5 caracteres')], verbose_name='Ubicacion')),
                ('EstadoBodega', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('En Mantenimiento', 'En Mantenimiento')], db_column='EstadoBodega', max_length=20, verbose_name='Estado de la bodega')),
                ('ObservacionesBodega', models.TextField(db_column='ObservacionesBodega', max_length=500, validators=[ProInvPunDeVenAPI.models.Bodegas.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(10, message='Debes ingresar mínimo 10 caracteres')], verbose_name='Observaciones sobre la bodega')),
            ],
            options={
                'db_table': 'Bodegas',
                'constraints': [models.UniqueConstraint(fields=('IdBodega',), name='unique_id_bodega')],
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('IdCargos', models.AutoField(db_column='IdCargos', primary_key=True, serialize=False, verbose_name='Id Cargo')),
                ('TipoDeCargo', models.CharField(choices=[('Etiquetador', 'Etiquetador'), ('Bodeguero', 'Bodeguero'), ('Ayudante', 'Ayudante'), ('Despachador', 'Despachador')], db_column='TipoDeCargo', max_length=20, verbose_name='Tipo de cargo')),
                ('EstadoDelCargo', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='EstadoDelCargo', max_length=10, verbose_name='Estado del cargo')),
                ('DescripcionDelCargo', models.TextField(db_column='DescripcionDelCargo', max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='Debe ingresar al menos 10 caracteres')], verbose_name='Descripcion del cargo')),
                ('SueldoBase', models.IntegerField(db_column='SueldoBase', validators=[django.core.validators.MinValueValidator(150000, message='Sueldo base minimo es de $150.000')], verbose_name='Sueldo base')),
            ],
            options={
                'db_table': 'Cargos',
                'constraints': [models.UniqueConstraint(fields=('IdCargos',), name='unique_id_cargos')],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('IdCategoriaProducto', models.AutoField(db_column='IdCategoriaProducto', primary_key=True, serialize=False, verbose_name='Id Categoria Producto')),
                ('NombreCategoria', models.CharField(db_column='NombreCategoria', max_length=20, validators=[ProInvPunDeVenAPI.models.CategoriaProducto.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(3, message='Debes ingresar minimo 3 caracteres')], verbose_name='Nombre de la categoria')),
                ('Descripcion', models.TextField(db_column='Descripcion', max_length=500, validators=[ProInvPunDeVenAPI.models.CategoriaProducto.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(10, message='Debes ingresar minimo 10 caracteres')], verbose_name='Descripcion')),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Pausado', 'Pausado')], db_column='Estado', max_length=10)),
                ('Observaciones', models.TextField(db_column='Observaciones', max_length=500, validators=[ProInvPunDeVenAPI.models.CategoriaProducto.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(10, message='Debes ingresar minimo 10 caracteres')], verbose_name='Observaciones')),
            ],
            options={
                'db_table': 'CategoriaProducto',
                'constraints': [models.UniqueConstraint(fields=('IdCategoriaProducto',), name='unique_id_categoria_producto')],
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('IdEmpleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('RutEmpleado', models.CharField(db_column='RutEmpleado', error_messages={'unique': 'El rut ingresado ya se encuentra registrado, Por favor, verifique.'}, max_length=10, validators=[ProInvPunDeVenAPI.models.Empleados.validacion_rut_real], verbose_name='Rut (01234567-k)')),
                ('NombreEmpleado', models.CharField(db_column='NombreEmpleado', max_length=20, validators=[ProInvPunDeVenAPI.models.Empleados.validacion_nombre_y_apellido_real, django.core.validators.MinLengthValidator(3, message='Por favor, ingrese un nombre real')], verbose_name='Nombre')),
                ('ApellidoEmpleado', models.CharField(db_column='ApellidoEmpleado', max_length=55, validators=[ProInvPunDeVenAPI.models.Empleados.validacion_nombre_y_apellido_real, django.core.validators.MinLengthValidator(3, message='Por favor, ingrese un apellido real')], verbose_name='Apellido')),
                ('EdadEmpleado', models.IntegerField(db_column='EdadEmpleado', validators=[ProInvPunDeVenAPI.models.Empleados.validacion_edad_negativa, django.core.validators.MinValueValidator(18, message='Debes tener al menos 18 años'), django.core.validators.MaxValueValidator(99, message='Edad invalida, no puede tener mas de 100 años')], verbose_name='Edad')),
                ('NumeroTelefonoEmpleado', models.IntegerField(db_column='NumeroTelefonoEmpleado', validators=[ProInvPunDeVenAPI.models.Empleados.validacion_largo_y_solo_numeros], verbose_name='Telefono (912345678)')),
            ],
            options={
                'db_table': 'Empleados',
                'constraints': [models.UniqueConstraint(fields=('IdEmpleado',), name='unique_id_empleado'), models.UniqueConstraint(fields=('RutEmpleado',), name='unique_rut_empleado')],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('CodigoDeBarras', models.CharField(db_column='CodigoDeBarras', error_messages={'unique': 'El código de barras ingresado ya se encuentra registrado. Por favor, verifique.'}, max_length=100, verbose_name='Código de Barras')),
                ('ValorProducto', models.IntegerField(db_column='ValorProducto', validators=[django.core.validators.MinValueValidator(1000, message='El valor minimo de un producto es de $1000')], verbose_name='Valor')),
                ('StockProducto', models.IntegerField(db_column='StockProducto', validators=[django.core.validators.MinValueValidator(1, message='El Stock minimo es de 1 unidad ')], verbose_name='Stock')),
                ('NombreProducto', models.CharField(db_column='NombreProducto', max_length=60, validators=[django.core.validators.MinLengthValidator(5, message='El nombre del producto debe tener al menos 5 caracteres.')], verbose_name='Nombre del producto')),
                ('FechaDeRegistroProducto', models.DateTimeField(auto_now_add=True, db_column='FechaDeRegistroProducto')),
                ('MarcaProducto', models.CharField(db_column='MarcaProducto', max_length=55, validators=[django.core.validators.MinLengthValidator(4, message='La marca del producto debe tener al menos 4 caracteres')], verbose_name='Marca')),
                ('FechaDeVencimiento', models.DateField(db_column='FechaDeVencimiento', validators=[ProInvPunDeVenAPI.models.Productos.validacion_fecha_de_vencimiento_futura], verbose_name='Fecha de vencimiento')),
                ('Bodegas', models.ForeignKey(blank=True, db_column='BodegaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto', to='ProInvPunDeVenAPI.bodegas')),
                ('CategoriaProducto', models.ForeignKey(blank=True, db_column='CategoriaProductoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto', to='ProInvPunDeVenAPI.categoriaproducto')),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IdUsuarios', models.AutoField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('Username', models.CharField(db_column='Username', error_messages={'unique': 'El username ingresado ya se encuentra ocupado, Por favor, intentelo con otro nuevamente.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(5, message='El username debe tener al menos 5 caracteres')])),
                ('Password', models.CharField(db_column='Password', max_length=128, validators=[ProInvPunDeVenAPI.models.Usuarios.validacion_password_segura, django.core.validators.MinLengthValidator(5, message='La password debe tener al menos 5 caracteres')])),
                ('CorreoElectronico', models.EmailField(db_column='CorreoElectronico', error_messages={'unique': 'El correo electronico ingresado ya se encuentra ocupado, Por favor, intentelo con otro nuevamente.'}, max_length=100, validators=[django.core.validators.EmailValidator(message='Debe ingresar un correo valido')], verbose_name='Correo electronico')),
                ('Cargo', models.ForeignKey(blank=True, db_column='CargoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo', to='ProInvPunDeVenAPI.cargos')),
                ('Empleado', models.ForeignKey(blank=True, db_column='EmpleadoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='ProInvPunDeVenAPI.empleados')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('IdAuditoriaUsuario', models.AutoField(db_column='IdAuditoriaUsuario', primary_key=True, serialize=False)),
                ('UsuarioIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('UsuarioNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_usuario_usuario', to='ProInvPunDeVenAPI.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaUsuario',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaProducto',
            fields=[
                ('IdAuditoriaProducto', models.AutoField(db_column='IdAuditoriaProducto', primary_key=True, serialize=False)),
                ('ProductoIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('ProductoNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Producto', models.ForeignKey(blank=True, db_column='ProductoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_producto', to='ProInvPunDeVenAPI.productos')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_producto_usuario', to='ProInvPunDeVenAPI.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaProducto',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEmpleado',
            fields=[
                ('IdAuditoriaEmpleado', models.AutoField(db_column='IdAuditoriaEmpleado', primary_key=True, serialize=False)),
                ('EmpleadoIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('EmpleadoNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Empleado', models.ForeignKey(blank=True, db_column='EmpleadoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_empleado', to='ProInvPunDeVenAPI.empleados')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_empleado_usuario', to='ProInvPunDeVenAPI.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaEmpleado',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCategoria',
            fields=[
                ('IdAuditoriaCategoria', models.AutoField(db_column='IdAuditoriaCategoria', primary_key=True, serialize=False)),
                ('CategoriaIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('CategoriaNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Categoria', models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_categoria', to='ProInvPunDeVenAPI.categoriaproducto')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_categoria_usuario', to='ProInvPunDeVenAPI.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaCategoria',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCargo',
            fields=[
                ('IdAuditoriaCargo', models.AutoField(db_column='IdAuditoriaCargo', primary_key=True, serialize=False)),
                ('CargoIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('CargoNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Cargo', models.ForeignKey(blank=True, db_column='CargoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_cargos', to='ProInvPunDeVenAPI.cargos')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_cargo_usuario', to='ProInvPunDeVenAPI.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaCargo',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaBodega',
            fields=[
                ('IdAuditoriaBodega', models.AutoField(db_column='IdAuditoriaBodega', primary_key=True, serialize=False)),
                ('BodegaIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('BodegaNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Bodega', models.ForeignKey(blank=True, db_column='BodegaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_bodegas', to='ProInvPunDeVenAPI.bodegas')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_bodega_usuario', to='ProInvPunDeVenAPI.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaBodega',
            },
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.UniqueConstraint(fields=('IdProducto',), name='unique_id_producto'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.UniqueConstraint(fields=('CodigoDeBarras',), name='unique_codigo_de_barras'),
        ),
        migrations.AddConstraint(
            model_name='usuarios',
            constraint=models.UniqueConstraint(fields=('IdUsuarios',), name='unique_id_usuarios'),
        ),
        migrations.AddConstraint(
            model_name='usuarios',
            constraint=models.UniqueConstraint(fields=('Username',), name='unique_username'),
        ),
        migrations.AddConstraint(
            model_name='usuarios',
            constraint=models.UniqueConstraint(fields=('CorreoElectronico',), name='unique_correo_electronico'),
        ),
        migrations.AddConstraint(
            model_name='auditoriausuario',
            constraint=models.UniqueConstraint(fields=('IdAuditoriaUsuario',), name='unique_id_auditoria_usuario'),
        ),
        migrations.AddConstraint(
            model_name='auditoriaproducto',
            constraint=models.UniqueConstraint(fields=('IdAuditoriaProducto',), name='unique_id_auditoria_producto'),
        ),
        migrations.AddConstraint(
            model_name='auditoriaempleado',
            constraint=models.UniqueConstraint(fields=('IdAuditoriaEmpleado',), name='unique_id_auditoria_empleado'),
        ),
        migrations.AddConstraint(
            model_name='auditoriacategoria',
            constraint=models.UniqueConstraint(fields=('IdAuditoriaCategoria',), name='unique_id_auditoria_categoria'),
        ),
        migrations.AddConstraint(
            model_name='auditoriacargo',
            constraint=models.UniqueConstraint(fields=('IdAuditoriaCargo',), name='unique_id_auditoria_cargo'),
        ),
        migrations.AddConstraint(
            model_name='auditoriabodega',
            constraint=models.UniqueConstraint(fields=('IdAuditoriaBodega',), name='unique_id_auditoria_bodega'),
        ),
    ]
