"""
Django settings for ProyectoInventarioPuntoDeVenta project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o53sd!o+xpkb90f*q#@in5$lllhjue9-imq3nh)s!eo3)qd*is'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

##SE DEFINE EL DICCIONARIO DE COMO SE COMPORATARA EL REST_FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES' :[ #LISTA QUE ESPECIFICA EL METODO DE AUTHENTICACION QUE SE USARA
        'rest_framework_simplejwt.authentication.JWTAuthentication',  ##LA API usará JSON Web Tokens (JWT) para autenticar a los usuarios
    ],
    'DEFAULT_PERMISSION_CLASSES': [ #LISTA DE PERMISOSQUE SE USARA
        'rest_framework.permissions.IsAuthenticated', #SE APLICA QUE A TODAS LAS VISTAS REQUIERAN DE TOKENS PARA FUNCIONAR
    ]
}

##
##El backend recibe el token, verifica que sea válido y no esté expirado, 
##luego identifica al usuario y lo asigna a request.user.
##y Si el token es inválido o expiró, la API responde con 401 o 403

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders', #SE IMPLEMENTA CORS COMO APP SEGUN EL PIP INSTALL PARA PODER USAR CORS
    'drf_yasg', #SE IMPLEMENTA SWAGGER COMO APP SEGUN PIP INSTALL PARA PODER GENERAR DOCUMENTACION AUTOMATICA CON UNA UI
    'ProInvPunDeVenAPI',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', #PERMITE O BLOQUEA PETICIONES DE SITIOS EXTERNOS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#SITIOS WEBS QUE SE LES PERMITIRA USAR LA API
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000'
]


ROOT_URLCONF = 'ProyectoInventarioPuntoDeVenta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectoInventarioPuntoDeVenta.wsgi.application'


#instalar mysql https://cdn.mysql.com//Downloads/MySQL-9.4/mysql-9.4.0-winx64.msi
#instalar mysql workbench https://cdn.mysql.com//Downloads/MySQLGUITools/mysql-workbench-community-8.0.43-winx64.msi

#poner en cmd en la carpeta del proyecto: pip install PyMySQL

import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'punto-de-venta-db',
        'USER': 'root',
        'PASSWORD': 'root'
    }
}

#utilizar cmd: python manage.py makemigrations
#despues: python manage.py migrate

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl' #Lenguaje pagina

TIME_ZONE = 'America/Santiago' # Zona horaria

USE_I18N = True # Traduccion de texto

USE_L10N = True #Fechas segun horario definido en Time_Zone

USE_TZ = True #Usa la zona horaria especificada en Time_Zone


##FORMATEO DE FECHAS PARA SER DIA-MES-AÑO
DATE_INPUT_FORMATS = ['%d-%m-%Y'] ##Define datos de fecha que django aceptara como validos
DATE_FORMAT = 'd-m-Y' ##Define como django mostrara las fechas


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
